version: '3.8'

services:
  db:
    image: postgres:17.5-alpine3.22
    container_name: sonzai-bank-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: sonzai-bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: sonzai@123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8085
    depends_on:
      - db
volumes:
  pgdata:
