// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: service_sonzai_bank.proto

package pb

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_service_sonzai_bank_proto protoreflect.FileDescriptor

const file_service_sonzai_bank_proto_rawDesc = "" +
	"\n" +
	"\x19service_sonzai_bank.proto\x12\x02pb\x1a\x1cgoogle/api/annotations.proto\x1a\x14rpc_login_user.proto\x1a\x15rpc_create_user.proto\x1a\x15rpc_update_user.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\x8f\x02\n" +
	"\n" +
	"SonZaiBank\x12W\n" +
	"\n" +
	"CreateUser\x12\x15.pb.CreateUserRequest\x1a\x16.pb.CreateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/create_user\x12O\n" +
	"\x05Login\x12\x14.pb.LoginUserRequest\x1a\x15.pb.LoginUserResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/login_user\x12W\n" +
	"\n" +
	"UpdateUser\x12\x15.pb.UpdateUserRequest\x1a\x16.pb.UpdateUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/update_userB\x86\x01\x92AY\x12W\n" +
	"\x0fSonZai Bank API\"?\n" +
	"\aSon Zai\x12\x19https://github.com/sonpv8\x1a\x19phanvanson.info@gmail.com2\x031.0Z(github.com/sonzai8/golang-sonzai-bank/pbb\x06proto3"

var file_service_sonzai_bank_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: pb.CreateUserRequest
	(*LoginUserRequest)(nil),   // 1: pb.LoginUserRequest
	(*UpdateUserRequest)(nil),  // 2: pb.UpdateUserRequest
	(*CreateUserResponse)(nil), // 3: pb.CreateUserResponse
	(*LoginUserResponse)(nil),  // 4: pb.LoginUserResponse
	(*UpdateUserResponse)(nil), // 5: pb.UpdateUserResponse
}
var file_service_sonzai_bank_proto_depIdxs = []int32{
	0, // 0: pb.SonZaiBank.CreateUser:input_type -> pb.CreateUserRequest
	1, // 1: pb.SonZaiBank.Login:input_type -> pb.LoginUserRequest
	2, // 2: pb.SonZaiBank.UpdateUser:input_type -> pb.UpdateUserRequest
	3, // 3: pb.SonZaiBank.CreateUser:output_type -> pb.CreateUserResponse
	4, // 4: pb.SonZaiBank.Login:output_type -> pb.LoginUserResponse
	5, // 5: pb.SonZaiBank.UpdateUser:output_type -> pb.UpdateUserResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_sonzai_bank_proto_init() }
func file_service_sonzai_bank_proto_init() {
	if File_service_sonzai_bank_proto != nil {
		return
	}
	file_rpc_login_user_proto_init()
	file_rpc_create_user_proto_init()
	file_rpc_update_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_sonzai_bank_proto_rawDesc), len(file_service_sonzai_bank_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_sonzai_bank_proto_goTypes,
		DependencyIndexes: file_service_sonzai_bank_proto_depIdxs,
	}.Build()
	File_service_sonzai_bank_proto = out.File
	file_service_sonzai_bank_proto_goTypes = nil
	file_service_sonzai_bank_proto_depIdxs = nil
}
