// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: service_sonzai_bank.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SonZaiBank_CreateUser_FullMethodName = "/pb.SonZaiBank/CreateUser"
	SonZaiBank_Login_FullMethodName      = "/pb.SonZaiBank/Login"
)

// SonZaiBankClient is the client API for SonZaiBank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SonZaiBankClient interface {
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error)
}

type sonZaiBankClient struct {
	cc grpc.ClientConnInterface
}

func NewSonZaiBankClient(cc grpc.ClientConnInterface) SonZaiBankClient {
	return &sonZaiBankClient{cc}
}

func (c *sonZaiBankClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, SonZaiBank_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sonZaiBankClient) Login(ctx context.Context, in *LoginUserRequest, opts ...grpc.CallOption) (*LoginUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginUserResponse)
	err := c.cc.Invoke(ctx, SonZaiBank_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SonZaiBankServer is the server API for SonZaiBank service.
// All implementations must embed UnimplementedSonZaiBankServer
// for forward compatibility.
type SonZaiBankServer interface {
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Login(context.Context, *LoginUserRequest) (*LoginUserResponse, error)
	mustEmbedUnimplementedSonZaiBankServer()
}

// UnimplementedSonZaiBankServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSonZaiBankServer struct{}

func (UnimplementedSonZaiBankServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedSonZaiBankServer) Login(context.Context, *LoginUserRequest) (*LoginUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedSonZaiBankServer) mustEmbedUnimplementedSonZaiBankServer() {}
func (UnimplementedSonZaiBankServer) testEmbeddedByValue()                    {}

// UnsafeSonZaiBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SonZaiBankServer will
// result in compilation errors.
type UnsafeSonZaiBankServer interface {
	mustEmbedUnimplementedSonZaiBankServer()
}

func RegisterSonZaiBankServer(s grpc.ServiceRegistrar, srv SonZaiBankServer) {
	// If the following call pancis, it indicates UnimplementedSonZaiBankServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SonZaiBank_ServiceDesc, srv)
}

func _SonZaiBank_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonZaiBankServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonZaiBank_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonZaiBankServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SonZaiBank_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SonZaiBankServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SonZaiBank_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SonZaiBankServer).Login(ctx, req.(*LoginUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SonZaiBank_ServiceDesc is the grpc.ServiceDesc for SonZaiBank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SonZaiBank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SonZaiBank",
	HandlerType: (*SonZaiBankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _SonZaiBank_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _SonZaiBank_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_sonzai_bank.proto",
}
