# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      DB_DRIVER.DB_HOST=postgres
      DB_DRIVER.DB_USER=root
      DB_DRIVER.DB_PASSWORD=sonzai@123456
      DB_DRIVER.DB_NAME=sonzai-bank
      DB_DRIVER.DB_PORT=5432
      DB_DRIVER.DB_SSLMODE=disable

    services:
      postgres:
        image: postgres:17.5-alpine3.22
        env:
          POSTGRES_DB: sonzai-bank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: sonzai@123456
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - "5432:5432"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
        id: go

      - name: Checkout cod into the Go module directory
        uses: actions/checkout@v4

      - name: install golang-migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.3/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          ls
          which migrate
      - name: Run migrate
        run: make migrate-up


      - name: Make Test
        run: make test
